### ISSUE TITLE
--keep-folder in combination with --torrenthash 

### ISSUE THREAD

**Issue by PunchDrunkL0ve** [Audionut/Upload-Assistant#103]
The combination of -kf and -th gives "Provided .torrent has files that were not expected" and forces the script to skip the folder and upload only the mkv file.

**Comment by Audionut** [comment]
I assume the actual torrents were an exact match.

**Comment by PunchDrunkL0ve** [comment]
Yes, was an attempt to x-seed.

**Comment by Audionut** [comment]
I'm seeing this with a single valid file inside of a folder.
``` python
           Torrent is valid based on disc/basename or keep-folder: True                                                                                                                                                                         clients.py:134
           Single file match status: valid=True, wrong_file=True                                                                                                                                                                                clients.py:144
           Checking piece size and count: pieces=5255, piece_size=2097152                                                                                                                                                                       clients.py:173
           Final validity after piece checks: valid=False  
```
I need to look at it further to find out why the valid status was changed to false at the end.

But it smells like you might be trying to match a folder with a valid file + other files, against the same torrents.
Keep folder will still discard nfo, sample, etc etc files from the folder, only using MKV or whatever. So if you try and match your folder+file to a torrent with folder+multiple files, that is an expected fail condition.

**Comment by PunchDrunkL0ve** [comment]
OK thanks.

In my case it was folder+single mkv file, so didn't expect the final validity check to fail. But that was 1of1 attempts to use -kf so far.

**Comment by Audionut** [comment]
Ah, I see `wrong_file=True` now. I tried it outside of debug and didn't get the same feedback as you. I'll look into it :)

**Comment by Audionut** [comment]
I was failing the piece size check, not sure why I didn't get the proper error feedback, I'll need to look into that.
