### ISSUE TITLE
Increase number of screenshots for individual episodes within a Series pack

### ISSUE THREAD

**Issue by PunchDrunkL0ve** [Audionut/Upload-Assistant#109]
Hi,

Some PTs require screenshots for every individual episode when uploading a series pack. With the exception of the 1st episode that obeys the setting in `config.py` please can the number of screenshots be increased to 'take 3 - upload 2' instead of the current 'take 2 - upload 1'.

Many thanks.

**Comment by Audionut** [comment]
Fixed in https://github.com/Audionut/Upload-Assistant/commit/ff147ff3653a74e4e7e24e269da643cea9945dbe
