### ISSUE TITLE
Torrent Path in qBittorrent

### ISSUE THREAD

**Issue by kam036** [Audionut/Upload-Assistant#123]
I'm using this with docker and everything is working great but when it adds the torrent to qBittorrent, it's using the remote (docker) path instead of the local path, (/downloads instead of /home/user/downloads/. I have specified local/remote paths in the Upload Assistant qBit config. Any ideas on how to correct this?

**Comment by MontejoJorge** [comment]
Hey @kam036 how do you fixed it?

**Comment by kam036** [comment]
Just do the opposite, local path is the docker path, remote is the path outside docker.
