### ISSUE TITLE
Incorrect naming when uploading to HUNO

### ISSUE THREAD

**Issue by AN1MATEK** [Audionut/Upload-Assistant#128]
Hi there,

I recently noticed that my torrents are being uploaded to HUNO without the language tag. For example:

`Name (2024) (1080p BluRay REMUX AVC SDR DTS-HD MA 5.1 - FraMeSToR)` instead of `Name (2024) (1080p BluRay REMUX AVC SDR DTS-HD MA 5.1 English - FraMeSToR)`

Staff mentioned that they are seeing this in a lot of uploads too. I just wanted to bring attention to the issue. 

Thanks and have a nice day 😎

**Comment by Audionut** [comment]
After this code https://github.com/Audionut/Upload-Assistant/commit/8c6887492aa666ffcf4bfe8aa9e4b46bb732636a

Are you on docker?

**Comment by AN1MATEK** [comment]
`Are you on docker?`

Yes I am.

**Comment by Audionut** [comment]
Thanks, but it's my fault, not docker.
