### ISSUE TITLE
Not finding existing .torrent files with qbittorrent 4.6.x

### ISSUE THREAD

**Issue by Schaka** [Audionut/Upload-Assistant#13]
Unless I pass the existing hash as an argument, it never seems to find the existing .torrent files.
This seems to be working perfectly on my dedi where I use qbittorrent 4.3.9.

It may be worth it for you to start using https://github.com/rmartin16/qbittorrent-api if you haven't already.
It keeps support for older versions afaik.

Other people seem to be having the same issues. But I haven't looked at the code and can't 100% confirm this is the issue. So don't waste too much time if you can't confirm it.

**Comment by Audionut** [comment]
Judging by the requirements text, that api is already being used. If you run in --debug mode, you should see this in the console after image uploading.

```
Searching qbittorrent for an existing .torrent
[22:10:14] C:\qbittorrent_4.6.5_lt20_qt6_x64_setup\profile\qBittorrent\data\BT_backup/2a2d47ba6.torrent                                                   clients.py:118
Found a matching .torrent with hash: 2a2ba6
           C:\qbittorrent_4.6.5_lt20_qt6_x64_setup\profile\qBittorrent\data\BT_backup/2a2ba6.torrent
```

I highly suspect this is a docker linking issue.

**Comment by Schaka** [comment]
Can be closed. I saw the API is already being used.
My mapping is correct. I helped a bunch of people set it up in the past few days and also made sure search is enabled.

It seems that sometimes it just doesn't use an existing torrent and sometimes it is. I've not been able to figure out the issue for myself.

**Comment by Audionut** [comment]
Thanks for responding. Here, it's only rarely that it fails to use an existing torrent. The next time I notice, I'll try to find the root cause of the issue.
