### ISSUE TITLE
[feature] Ability to define a proxy in config

### ISSUE THREAD

**Issue by GordonFreemanK** [Audionut/Upload-Assistant#133]
Would be nice to be able to define a proxy to use when doing requests to trackers (or any, really). This could be done using the built-in `requests.get` parameter e.g. `requests.get(url, proxies={'https':'http://192.168.0.1:3130'})`

I don't know how many people this could be useful for but I suspect this is the source of an issue I have uploading to a tracker: I normally browse the tracker website through a local proxy connected to a VPN ([gluetun](https://github.com/qdm12/gluetun)) but upload.py is connecting directly through my home IP. Possibly the tracker is refusing connections from two IPs at the same time? Anyway even if this isn't the issue if other people are doing VPN through proxies they might find this useful anyway.

I'd create a PR myself but I have [this issue](https://github.com/Audionut/Upload-Assistant/issues/132) running locally.

**Comment by Audionut** [comment]
This is outside of scope. This is an upload assistant, not a network manager. If you have gluetun running and connections through both your local ethernet and vpn, then it sounds like you have split tunneling working, and need to correctly tunnel python as needed.

**Comment by GordonFreemanK** [comment]
Makes sense, I'll do that. Thanks for replying.
