### ISSUE TITLE
Saving Screens Stalls When Uploading .Isos

### ISSUE THREAD

**Issue by ThoughtzThruKeyz** [Audionut/Upload-Assistant#145]
Title pretty much sums up the issue, I get stuck on:
`Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/6 -:--:--`

When trying to upload like full DVD or .Iso releases. Are these not supported?

**Comment by Audionut** [comment]
ISO is not supported.

https://github.com/Audionut/Upload-Assistant/discussions/46
