### ISSUE TITLE
Freezing on title confirmation

### ISSUE THREAD

**Issue by kam036** [Audionut/Upload-Assistant#155]
I'm running into an issue with upload assistant freezing on the "Is this correct?" title confirmation when trying to upload to AITHER. BHD uploads have been working fine. I'm using docker and have tried both the master and latest tags

**Comment by Audionut** [comment]
If you're using docker can you test `docker pull ghcr.io/audionut/upload-assistant:development` and make sure you have the config option set https://github.com/Audionut/Upload-Assistant/blob/96fbd38ba408248a7079c5192dc565c4d8a87ced/data/example-config.py#L36

**Comment by kam036** [comment]
Unfortunately still running into the same issue. I have tried a couple different files. It also froze on a BHD upload, so it doesn't appear to be AITHER specific.

Here's a copy of my config if it helps - [https://pastebin.com/raw/PkrR13Md](url)

**Comment by Audionut** [comment]
Exposed, change credentials to be sure.

**Comment by kam036** [comment]
After trying a couple more AITHER uploads with the development tag, I'm no longer getting stuck at title confirmation, but after inputting Y to upload to Aither, it starts capturing 4 screenshots, optimizing 3 screenshots in a loop.

**Comment by kam036** [comment]
My apologises, the  capturing screenshots loop was due to multiscreens option, which I needed to turn off. I haven't run into that before.
