### ISSUE TITLE
imgbb, ptscreens, oeimg and lensdump are all broken

### ISSUE THREAD

**Issue by tiberio87** [Audionut/Upload-Assistant#156]
Log of upload:
`Gathering info for *.*.2024.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-*.mkv
SRRDB: No match found
Exporting MediaInfo...
MediaInfo Exported.
No matches found on any trackers.
Capturing Screenshots: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:14<00:00,  2.82s/it]
Optimizing Images: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:11<00:00,  2.86s/it]
Successfully captured 4 screenshots.
Final Edition: 
Uploading Images to imgbb: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.14s/it]
Failed to upload: 'Response' object is not subscriptable
Failed to upload: 'Response' object is not subscriptable
Failed to upload: 'Response' object is not subscriptable
Failed to upload: 'Response' object is not subscriptable
Successfully uploaded 0 images.`

**Comment by Audionut** [comment]
Just that host? I can't test them as they're paid.

I was going to tie in host uploading with `https://github.com/Audionut/Upload-Assistant/blob/eed6b28161763acf13ac3fd97275374a050ebf0e/data/example-config.py#L36` from the dev branch, but decided against. Might need to have an option for hosts if this one needs 1 image at a time.

**Comment by tiberio87** [comment]
imgbb

**Comment by Audionut** [comment]
Only imgbb?

**Comment by Audionut** [comment]
I just remembered I put a manual over ride for images into the code:
https://github.com/Audionut/Upload-Assistant/blob/96fbd38ba408248a7079c5192dc565c4d8a87ced/src/prep.py#L3009

You can set some host there with a value of 1 to override and revert to 1 image uploaded at a time and see if that helps.

**Comment by Audionut** [comment]
All these hosts seem broken. Looking into it.

**Comment by tiberio87** [comment]
The script uploads the images, in fact going to the imgbb control panel I find them. The script however gives that error and does not load them on the tracker.

**Comment by Audionut** [comment]
Can you try the development branch?

`docker pull ghcr.io/audionut/upload-assistant:development`

OEimg is working here, ptscreens constantly times out, and I don't have imgbb api key

**Comment by tiberio87** [comment]
> Can you try the development branch?
> 
> `docker pull ghcr.io/audionut/upload-assistant:development`
> 
> OEimg is working here, ptscreens constantly times out, and I don't have imgbb api key

I don't use docker, I use the phyton version.

**Comment by Audionut** [comment]
`https://github.com/Audionut/Upload-Assistant/tree/development`

I bumped the timeout to 60 seconds, and 1 image succeeded on ptscreens. I think there's some issue in how the code is handling responses from that api type, rather than some host throttling.

**Comment by tiberio87** [comment]
Until yesterday it worked well, they will have changed something on the host side. I have to try with your modification in development

**Comment by Audionut** [comment]
Indeed. I tried with some much older code and host problems still persist.

**Comment by eldarrarr** [comment]
I've used the `checker` tag on my container with success FYI, so _some_ older code works.

**Comment by eldarrarr** [comment]
Maybe worth trying reverting to this, maybe the new response fetching isn't working as intended?
```py
img_url = response['data']['image']['url']
raw_url = img_url
web_url = img_url
```

**Comment by Martzy303** [comment]
Problems seems to be in src/prep.php line 2882:
Instead of

`img_url = response['data'].get('medium', response['data']['image'])['url']`

Should be

`img_url = response_data['data'].get('medium', response_data['data']['image'])['url']`

**Comment by Audionut** [comment]
There's updated code in the development branch that needs to be confirmed. See comment above.

**Comment by suncokret12** [comment]
I tested the changes, and they successfully resolved the issue. Thank you!

**Comment by tiberio87** [comment]
New error with last release
`[*@*-*: $~/git/Upload-Assistant]$ python3.12 upload.py /*/*/*/*/sonarr/*.*.*.S02.1080p.NF.WEB-DL.DDP5.1.H.264-*/
Gathering info for *.*.*.S02.1080p.NF.WEB-DL.DDP5.1.H.264-*
SRRDB: No match found
No matches found on any trackers.
All screenshots already exist. Skipping capture process.
Successfully captured 0 screenshots.
Final Edition:
Uploading Images to imgbb:   0%|                                                                                                                                                                                                                        | 0/4 [00:00<?, ?it/s]imgbb failed, trying next image host
Uploading Images to imgbb:  25%|████████████████████████████████████████████████████                                                                                                                                                            | 1/4 [00:01<00:03,  1.30s/it]imgbb failed, trying next image host
Uploading Images to imgbb:  50%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                        | 2/4 [00:03<00:03,  1.98s/it]imgbb failed, trying next image host
Uploading Images to imgbb:  75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                    | 3/4 [00:05<00:01,  1.73s/it]imgbb failed, trying next image host
Uploading Images to imgbb: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.64s/it]
Failed to upload: imgbb upload failed
Failed to upload: imgbb upload failed
Failed to upload: imgbb upload failed
Failed to upload: imgbb upload failed
Successfully uploaded 0 images.
Prep material saved to /*/*/git/Upload-Assistant/tmp/*.*.*.S02.1080p.NF.WEB-DL.DDP5.1.H.264-*`

**Comment by suncokret12** [comment]
> loa

If you don't have imgbb premium account, at one point it won't let you upload to it with API anymore, so that might be the problem, however it should switch to a next host in your config, unless you removed the lines. I set it to use ptscreens by default and it's working fine, and if ptscreens fails in some cases, it would move to imgbox and upload with no problems.

**Comment by Audionut** [comment]
Indeed, switching host is something I broke.

**Comment by Audionut** [comment]
I secured a free api key, imgbb is now working here

**Comment by tiberio87** [comment]
Everything's working now, thank you.
