### ISSUE TITLE
Feature - Rehost images for BHD

### ISSUE THREAD

**Issue by edge20200** [Audionut/Upload-Assistant#160]
Rehost images to an approved image host same as MTV.

**Comment by Audionut** [comment]
The only limitation I am observing in their rules is that all hosts must support SSL, which I believe they all do.

I added a catch here to ensure ptpimg urls pulled from descriptions are always https 
https://github.com/Audionut/Upload-Assistant/commit/41548a42baf34ca2f0dd46b3cad2d20ddd26c0d1

Can you expand?
