### ISSUE TITLE
Confirm path of /BT_Backup before capturing screenshots

### ISSUE THREAD

**Issue by jordanlambrecht** [Audionut/Upload-Assistant#164]
Otherwise you spend 5 minutes capturing the screenshots just for the script to fail

**Comment by Audionut** [comment]
This is not the end of the world. Even a lack of bt_backup can be worked around. Fix the bt_backup folder, which you should really be doing anyway if you want to really enjoy this, then just run the same command again. It will skip through the tasks already completed.
