### ISSUE TITLE
Failed to upload images to IMGBB

### ISSUE THREAD

**Issue by deitybob12** [Audionut/Upload-Assistant#207]
Today I am getting errors of the script be unable to upload images to IMGBB. I verified my API key, my account status, and manual uploads to IMGBB to be working and correct. Did something about their API change or are they unstable today?

I am running the Upload-Assistant release as of today. 

Uploading Images to imgbb:   0%|                                                                                                  | 0/6 [00:00<?, ?it/s]imgbb failed, trying next image host
Uploading Images to imgbb:  17%|###############                                                                           | 1/6 [00:03<00:19,  3.99s/it]imgbb failed, trying next image host
Uploading Images to imgbb:  33%|##############################                                                            | 2/6 [00:05<00:09,  2.44s/it]imgbb failed, trying next image host
Uploading Images to imgbb:  50%|#############################################                                             | 3/6 [00:06<00:05,  1.87s/it]imgbb failed, trying next image host
Uploading Images to imgbb:  67%|############################################################                              | 4/6 [00:07<00:03,  1.67s/it]imgbb failed, trying next image host
Uploading Images to imgbb:  83%|###########################################################################               | 5/6 [00:09<00:01,  1.57s/it]imgbb failed, trying next image host
Uploading Images to imgbb: 100%|##########################################################################################| 6/6 [00:10<00:00,  1.79s/it]
Failed to upload: imgbb upload failed
Failed to upload: imgbb upload failed
Failed to upload: imgbb upload failed
Failed to upload: imgbb upload failed
Failed to upload: imgbb upload failed
Failed to upload: imgbb upload failed

**Comment by Audionut** [comment]
Something on your/their end.
