### ISSUE TITLE
Pass dupe checks but should still ask if want to upload. 

### ISSUE THREAD

**Issue by edge20200** [Audionut/Upload-Assistant#215]
Newest version now try's to auto-upload to every tracker if it pass's dupe checks instead of asking while there may not be a dupe content could still not be allowed on tracker because of quality or other reasons. Should by default still ask if you want to upload to each tracker on list you have enabled.

**Comment by Audionut** [comment]
If it's not allowed on the tracker, then the tracker site file should be properly modified.

I'm tempted to leave it be if that's what it takes to get people to give proper feedback.

**Comment by 0zACPzg** [comment]
This is what I was asking about in my discussion. https://github.com/Audionut/Upload-Assistant/discussions/241
Sorry if this reopens the issue.
