### ISSUE TITLE
skip_if_rehash MTV issue?

### ISSUE THREAD

**Issue by backstab5983** [Audionut/Upload-Assistant#217]
Anyone else can reproduce? 

In my config.py under MTV section I have: 

```
'skip_if_rehash' : False,
'prefer_mtv_torrent' : True,
```

though when uploaded a torrent to MTV got:

`Piece size is OVER 8M and skip_if_rehash enabled. Skipping upload.`

**Comment by Audionut** [comment]
Sorry, I should have reopened this.

The proper fix is here https://github.com/Audionut/Upload-Assistant/commit/2b5055a5e27fcb4f34e5e87f078fe5d9f393f68a

You can pull the master branch if running native, but I've also just created a docker build https://github.com/Audionut/Upload-Assistant/pkgs/container/upload-assistant/327602810?tag=master
