### ISSUE TITLE
imgbox not a supported image host

### ISSUE THREAD

**Issue by TJZine** [Audionut/Upload-Assistant#29]
After updating the script recently I am not running into an error telling me imgbox is not a supported host. When I looked into the code very briefly it seems the if statement that handles uploading to imgbox in prep.py's upload_screens function may have been removed during a refactor.

**Comment by bencollinz** [comment]
I was coming to post the exact same thing. The code for imgbox is missing.

**Comment by Audionut** [comment]
Pretty damn slow host here, but fixed. I can't recall if this was the host that had a borked progress bar, but it works.
