### ISSUE TITLE
Requesting Support For New Site: Private Silver Screen (PSS)

### ISSUE THREAD

**Issue by SiskoUrso** [Audionut/Upload-Assistant#37]
Reaching out to put in a request for a new tracker, Private Silver Screen (PSS) https://privatesilverscreen.cc/ , It uses Unit3d.

Let me know if you need any further details.

**Comment by Audionut** [comment]
You can look at the changes https://github.com/Audionut/Upload-Assistant/pull/23/files and https://github.com/Audionut/Upload-Assistant/pull/25/files for an idea of how to add a UNIT3D site. You can use an existing UNIT3D site file as a template, or https://github.com/Audionut/Upload-Assistant/blob/master/src/trackers/UNIT3D_TEMPLATE.py

The biggest issues that need site access and to be changed, are the ID's https://github.com/Audionut/Upload-Assistant/blob/decfa5e1668d63bd252973dc0a36e457fe388893/src/trackers/UNIT3D_TEMPLATE.py#L37

These are generally slightly different for each site. You can go to your site, browse the torrents, open the advanced search panel, and then individually click each category, type and resolution, and watch what numbers are returned in the url bar. This will show you what numbers should be used for each ID in the site file. Make sure the URL's in the site file are correct https://github.com/Audionut/Upload-Assistant/blob/decfa5e1668d63bd252973dc0a36e457fe388893/src/trackers/UNIT3D_TEMPLATE.py#L31 (should only need a domain change, 

The self.tracker should be what you are calling the site. So if you are using PSS, you would use that at self.trackerand all areas where you refer to the site, like https://github.com/Audionut/Upload-Assistant/pull/23/files#diff-79121935774362ae6d2fd9619f64fcdaea2104da659a1eeeb240b636b9222ad8R39

Then just make sure to also change https://github.com/Audionut/Upload-Assistant/blob/decfa5e1668d63bd252973dc0a36e457fe388893/src/trackers/UNIT3D_TEMPLATE.py#L12 to site label (PSS in this instance) and you should be good to go.

If the site has unique rules and/or naming scheme, this would require much more work. If you're committed, there's an example of naming editing https://github.com/Audionut/Upload-Assistant/pull/23/files#diff-a7bbaf70a34d73c89cc77396ee88b783b54baece93372e63bf7b6a4a8fc73472R180 with a more comprehensive example https://github.com/Audionut/Upload-Assistant/blob/decfa5e1668d63bd252973dc0a36e457fe388893/src/trackers/HUNO.py#L131

**Comment by SiskoUrso** [comment]
Thanks for the details, I will work on this later and hopefully put in a PR soon with it.

**Comment by SiskoUrso** [comment]
Think everything is in order, put in the pr at #38
