### ISSUE TITLE
Commentary English track detected as dub can't be corrected

### ISSUE THREAD

**Issue by backstab5983** [Audionut/Upload-Assistant#51]
I've had a couple of occasions in which the commentary track has been detected as a secondary dub track hence the torrent gets titled as Dual-Audio, I tried in the corrections to add --no-dub or --no-dual / --no-dual-audio (I guess these 2 aren't an option) without luck.

Would a be a nice improvement to have :)

**Comment by Audionut** [comment]
Yeah, I've caught this one since the beginning about 3 times also. I've been lazy and just commented out the offending code previously, but a proper fix would be nice.

**Comment by Audionut** [comment]
This should get fixed with https://github.com/Audionut/Upload-Assistant/issues/53
