### ISSUE TITLE
Add save path as possible arg

### ISSUE THREAD

**Issue by backstab5983** [Audionut/Upload-Assistant#55]
Perhaps I'm doing something wrong or manually that's not needed, but in many cases the .mkv file is nested into a folder (often pointless as no subs or .nfo files have been added). Some trackers e.g. ANT don't allow folder uploads, hence the only way I'm doing now is uploading then changing manually the location of the file, but that triggers a recheck that is quite slow. 

Would implementing the save path of the file as arg be the best solution for the problem? 

I only saw the -kf option but shouldn't be helpful in this scenario.

**Comment by Audionut** [comment]
Torrents are hashed against files and folders, so if your only existing hashes include the parent folder, then it will require a rehash if you only want to upload the file.

**Comment by Audionut** [comment]
> hence the only way I'm doing now is uploading then changing manually the location of the file

I'm missing something here. If you point to a folder with mkv, and **not** use -kf `path "c:\my_mkv_is_in_this_folder"`, or point to the actual mkv file inside of a folder `path "c:\my_mkv_is_in_this_folder\this_is_my_mkv.mkv",` it will create a torrent based on that file, with the file location saved.

When it's injected into the client, _it should_, point to the actual file location without any manual adjustment or rehashing.

**Comment by bencollinz** [comment]
> > hence the only way I'm doing now is uploading then changing manually the location of the file
> 
> I'm missing something here. If you point to a folder with mkv, and **not** use -kf `path "c:\my_mkv_is_in_this_folder"`, or point to the actual mkv file inside of a folder `path "c:\my_mkv_is_in_this_folder\this_is_my_mkv.mkv",` it will create a torrent based on that file, with the file location saved.
> 
> When it's injected into the client, _it should_, point to the actual file location without any manual adjustment or rehashing.

Exactly. I think this is user misunderstanding issue.

**Comment by Audionut** [comment]
Automatic torrent management mode + default save location for a category + injecting into qbittorrent with that category, will absolutely have the torrent file point to the default save location for the category, regardless of anything else.

Injecting a torrent without using a category will not engage ATMM. You could use a tag instead.

I have ATMM enabled with some specific categories for the *arrs to work, everything else just uses tags so that it works with ATMM enabled.
