### ISSUE TITLE
Script re-uploads already uploaded screenshots when image host fails

### ISSUE THREAD

**Issue by PunchDrunkL0ve** [Audionut/Upload-Assistant#62]
Hello,

I'm frequently having an issue while uploading screenshots. My default image host is ptpimg. Very often the script will successfully upload the first couple of screenshots to ptpimg and then give an error that the image host has failed. When it attempts to upload the remaining screenshots to the next configured image host, instead of continuing from where it was left (ie with screenshot 3 of 6, 4 of 6, etc), it starts re-uploading the screenshots from the beginning (ie with screenshot 1 of 6). So I end up with having duplicate screenshots in my meta.json file.

I've tried using other image hosts as default but got the same issue so don't think it's related to ptpimg.

The confusing thing is that sometimes when there is an image host failure the script does 'remember' which screenshots are left to be uploaded to the next image host -which is the expected behaviour.

Any ideas/suggestions on how to solve the above issue would be very welcomed. Many thanks.

**Comment by Audionut** [comment]
See existing: https://github.com/L4GSP1KE/Upload-Assistant/issues/343

I tried refactoring this one by placing good uploads into a separate meta, but failed spectacularly.
I thought I had improved it, at least a little. I thought I had it set so that it continued with the next host, from the next image, rather than uploading the entire set again.

Did you still see the same problems in this repo?

**Comment by PunchDrunkL0ve** [comment]
Hiya,

Thanks for your response. The https://github.com/L4GSP1KE/Upload-Assistant/issues/343 is mine too but I think this repo is far more active than L4G's -bless him, so posted here too.

I'm still experiencing the issue with https://github.com/Audionut/Upload-Assistant/tree/master. Do you want me to try with https://github.com/Audionut/Upload-Assistant/tree/image_uploading?

Appreciate the time you're spending on this 🙏

**Comment by Audionut** [comment]
Yeah, if you can pull and test from that branch that would be awesome. I haven't tested at all yet, and need to get something else done. Plus I very rarely experience issues uploading, and I'm not sure I can kill a connection to a host quick enough to simulate.

Basically 2 reasons I implemented support for using existing image links in parsed descriptions:
- be kind to hosts
- side-step image uploading issues like this.

**Comment by PunchDrunkL0ve** [comment]
Will do, thanks. I'm very grateful we can re-use screenshoots with your repo, has helped me a lot recently.

I understand how difficult it is to reproduce my issue, so I went through my cmd history and found this -if it's of any help.

Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 0:00:00
Edition After Manual Edition:
Repack after Checks:
Uploading Screens... -------------------- ------------------- 2/4 0:00:29Failed to upload screeenshot-2.png to ptpimg. Exception: HTTPSConnectionPool(host='ptpimg.me',
port=443): Max retries exceeded with url: /upload.php (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of
protocol (_ssl.c:2406)')))
Uploading Screens... -------------------- ------------------- 2/4 0:00:29
                                            Uploading Screens...4
Uploading Screens... -------------------- ------------------- 2/4 0:00:29
Uploading Screens... -------------------- ------------------- 2/4 0:00:51

**Comment by Audionut** [comment]
I run that connection error through chatgtp, and it responded:

> The error you're encountering (SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol)) indicates that there's an issue with the SSL connection to ptpimg.me`, likely due to the SSL protocol being violated or an issue with the server's response.

Most of the solution resolved around backing off on the retry, which wouldn't seem to help (I've actually reduced the retry timer in this branch). The only other reasonable solution (apart from changing hosts which already occurs):

> Update requests and certifi Packages:
Ensure that you are using the latest version of requests and certifi (which handles SSL certificates). Sometimes, older versions of these libraries have bugs that cause SSL issues.

`pip install --upgrade requests certifi`

**Comment by PunchDrunkL0ve** [comment]
Thanks. Just checked and both `requests` and `certifi` are up-to-date.

Also, `git branch -a` doesn't list either of the two branches available. How do I pull the `image_uploading` branch?

**Comment by Audionut** [comment]
I'm a dumb GUI user, but `git pull origin image_uploading` should work.

If you want to test the changes without messing with pulled master branch, you can just grab the zip of the branch, and run upload-assistant from the extracted zip.
https://github.com/Audionut/Upload-Assistant/archive/refs/heads/image_uploading.zip

**Comment by PunchDrunkL0ve** [comment]
> I'm a dumb GUI user, but `git pull origin image_uploading` should work.

Not a `git` expert here either but your suggestion worked and will be testing shortly. You've given me tremendous help so far, can't thank you enough.

**Comment by Audionut** [comment]
Just had a chance to test locally, the timeout is set to low. Did allow me to test what happens when a host fails though, and that didn't correctly set the upload success save state.

Will push some more code shortly.

**Comment by PunchDrunkL0ve** [comment]
This is what I got so far. It did screenshot -1 and screenshot-2 then it errored out but continued with screenshot-3, which I think it's an improvement? Usually it goes back to screenshot-1.

Reusing screenshots
Edition After Manual Edition:
Repack after Checks:
Uploading Screens... -------------------- ------------------- 2/4 0:00:24Failed to upload screenshot-3.png to imgbb. Attempt 1/3. Exception: ('Connection aborted.',
TimeoutError('The write operation timed out'))
Uploading Screens... -------------------- ------------------- 2/4 0:00:24Failed to upload screenshot-3.png to imgbb. Attempt 2/3. Exception:
HTTPSConnectionPool(host='api.imgbb.com', port=443): Max retries exceeded with url: /1/upload (Caused by
SSLError(SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2406)')))
Uploading Screens... -------------------- ----------------Unsupported image host: imgbox All image hosts failed. Unable to complete uploads.
Uploading Screens... ------------------------------ --------- 3/4 -:--:--

**Comment by Audionut** [comment]
Pushed some more code, seems fine here when driving the hosts hard to test fallback, successful uploading state.

```python
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/6 -:--:--Failed to upload 47 Ronin-0.png to ptpimg. Attempt 1/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=1.1146443213117805)
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/6 -:--:--Failed to upload 47 Ronin-0.png to ptpimg. Attempt 2/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=1.9867991608128335)
Uploading Screens... ━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/6 -:--:--Failed to upload 47 Ronin-1.png to ptpimg. Attempt 1/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=1.3496654260169691)
Uploading Screens... ━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/6 -:--:--Failed to upload 47 Ronin-1.png to ptpimg. Attempt 2/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=1.8575607747625402)
Uploading Screens... ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/6 0:01:00Failed to upload 47 Ronin-3.png to ptpimg. Attempt 1/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=1.1663810820455538)
Uploading Screens... ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/6 0:01:00Failed to upload 47 Ronin-3.png to ptpimg. Attempt 2/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=1.66865354758122)
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 3/6 0:00:43Failed to upload 47 Ronin-4.png to ptpimg. Attempt 1/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=1.4190731502397234)
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 3/6 0:00:43Failed to upload 47 Ronin-4.png to ptpimg. Attempt 2/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=2.2282486306645923)
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 3/6 0:00:43Failed to upload 47 Ronin-4.png to ptpimg. Attempt 3/3. Exception: HTTPSConnectionPool(host='ptpimg.me', port=443): Read timed out. (read timeout=2.7787434186016173)
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 3/6 0:00:43Max retries reached for ptpimg. Moving to next image host.
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 3/6 0:00:43
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 -:--:--Unsupported image host: imgbox
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 -:--:--
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 -:--:--Failed to upload 47 Ronin-4.png to ptscreens. Attempt 1/3. Exception: HTTPSConnectionPool(host='ptscreens.com', port=443): Read timed out. (read timeout=1.9388127072110888)
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 -:--:--Failed to upload 47 Ronin-4.png to ptscreens. Attempt 2/3. Exception: HTTPSConnectionPool(host='ptscreens.com', port=443): Read timed out. (read timeout=1.7418967844859778)
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 -:--:--Failed to upload 47 Ronin-4.png to ptscreens. Attempt 3/3. Exception: HTTPSConnectionPool(host='ptscreens.com', port=443): Read timed out. (read timeout=3.0508042897445797)
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 -:--:--Max retries reached for ptscreens. Moving to next image host.
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 -:--:--
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 -:--:--Failed to upload 47 Ronin-4.png to pixhost. Attempt 1/3. Exception: ('Connection aborted.', TimeoutError('The write operation timed out'))
Uploading Screens... ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 -:--:--Failed to upload 47 Ronin-5.png to pixhost. Attempt 1/3. Exception: ('Connection aborted.', TimeoutError('The write operation timed out'))
Uploading Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 0:00:00
[
    {'img_url': 'https://ptpimg.me/js8b74.png', 'raw_url': 'https://ptpimg.me/js8b74.png', 'web_url': 'https://ptpimg.me/js8b74.png'},
    {'img_url': 'https://ptpimg.me/388n87.png', 'raw_url': 'https://ptpimg.me/388n87.png', 'web_url': 'https://ptpimg.me/388n87.png'},
    {'img_url': 'https://ptpimg.me/n39m12.png', 'raw_url': 'https://ptpimg.me/n39m12.png', 'web_url': 'https://ptpimg.me/n39m12.png'},
    {'img_url': 'https://t99.pixhost.to/thumbs/911/517395081_file-upload-0.png', 'raw_url': 'https://img99.pixhost.to/images/911/517395081_file-upload-0.png', 'web_url': 'https://pixhost.to/show/911/517395081_file-upload-0.png'},
    {'img_url': 'https://t99.pixhost.to/thumbs/911/517395128_file-upload-0.png', 'raw_url': 'https://img99.pixhost.to/images/911/517395128_file-upload-0.png', 'web_url': 'https://pixhost.to/show/911/517395128_file-upload-0.png'},
    {'img_url': 'https://t99.pixhost.to/thumbs/911/517395150_file-upload-0.png', 'raw_url': 'https://img99.pixhost.to/images/911/517395150_file-upload-0.png', 'web_url': 'https://pixhost.to/show/911/517395150_file-upload-0.png'}
]
```

**Comment by PunchDrunkL0ve** [comment]
wow great. Let me d/l the PR and test :)

**Comment by PunchDrunkL0ve** [comment]
Success for me too. Will keep testing before you merge.

Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 0:00:00
Edition After Manual Edition:
Repack after Checks:
                                           Uploading Screens...3. png to ptpimg. Attempt --------------------1 /-------------------3 . Exception: 2/4
 HTTPSConnectionPool0:00:24(host='ptpimg.me', port=443): Max retries exceeded with url: /upload.php (Caused by
SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2406)')))
Uploading Screens... ------------------------------ --------- 3/4 0:00:28Failed to upload screenshot-4.png to ptpimg. Attempt 1/3. Exception:
HTTPSConnectionPool(host='ptpimg.me', port=443): Max retries exceeded with url: /upload.php (Caused by
SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2406)')))
Uploading Screens... ---------------------------------------- 4/4 0:00:00
