### ISSUE TITLE
Skip upload when id & description found on tracker

### ISSUE THREAD

**Issue by DefectiveDev** [Audionut/Upload-Assistant#67]
You check sites to copy existing description and images. If it found on a tracker it should probably skip asking you to upload there.  Nothing major just little annoyance of clicking extra no.

**Comment by Audionut** [comment]
Use a site ID or `--unattended`

**Comment by DefectiveDev** [comment]
not what i meant. 
Say for example it matches the name and pull description from site x. then when scripts get to the upload part with trackers. It asks you to upload to site x which it pulled the description from. It already exists there since pulled the description and images. It should ask to upload to it.

**Comment by Audionut** [comment]
You're right.

But it would need the proper state checking, and frankly it's easier just to hit enter when prompted (default when uploading to tracker is No).
