### ISSUE TITLE
Imgbox loops the same image file during upload

### ISSUE THREAD

**Issue by Zips-sipZ** [Audionut/Upload-Assistant#77]
I've noticed myself and in modq that users who use imgbox upload the same image for all their images.
While it is the same image, it's all different URL's so it appears the scripts loops through the upload process fine but doesn't change source during the loop to go to next image for the upload.

I've tried myself to take a look at the code why this is but am not deep enough in it yet to see why this would happen, so creating this issue to make you aware.

**Comment by Audionut** [comment]
Thanks for the report, and sorry for the drama it's caused. Will file an issue about this shortly and reach back to you privately.
