### ISSUE TITLE
MTV Upload Error (Presentation Size Limit)

### ISSUE THREAD

**Issue by TJZine** [Audionut/Upload-Assistant#82]
After the latest changes to use full size images for MTV uploads I was getting an error uploading a UHD encode,
![image](https://github.com/user-attachments/assets/46b346e1-bed3-4a00-b212-2b4073736133)
After checking the bug thread purges, they are only meant to happen when there are no other copies of the media on site which was not true for my upload. I attempted to manually upload using the description L4G created for the upload and received an error stating the presentation was above the 25mb limit.
![image](https://github.com/user-attachments/assets/89f11bae-9b75-47ae-9f02-4354ac5a90e5)
Uploading the images manually and choosing thumbnails for the BB-code fixed the presentation size error and the manual upload went through.

**Comment by Audionut** [comment]
Because of the way they signal error, with an overlay, it doesn't seem easy to catch the error feedback.

With regards to the images, was it the case that the total size of all images exceeded 25 MiB, or was there a single image that exceeded that size limit?

**Comment by TJZine** [comment]
It was the total size of the images. Here are the sizes of the screenshots: 
![image](https://github.com/user-attachments/assets/0a8c6a31-4d1f-4822-ad14-9159c60cf7ea)

**Comment by Audionut** [comment]
Yes, optimization will generate a hefty reduction in screen sizes. If you know how to edit files on the seedbox, you could try editing the level on the following line to 1.

https://github.com/Audionut/Upload-Assistant/blob/70610a193eecd1a38d3f336da30672f67ec0330b/src/prep.py#L1474

`oxipng.optimize(image, level=1)`

And see if that fixes the memory errors. I bumped that to level 3 long ago for a little extra lossless compression, but if it's causing errors that result in people not being able to use optimization at all, it's worth putting it back to level 1.

I'll try and add a catch for MTV in any event, to skip images so that the total size remains within the constraint.

**Comment by TJZine** [comment]
Thanks so much for the quick fix! I may open another issue about the memory allocation with optimize images to create a pull request for as I have done some testing with the line you mentioned in the past and may have a way to fix the issue for anyone else on a shared seedbox who might run into it.

**Comment by Audionut** [comment]
That would be awesome, thanks.

**Comment by TJZine** [comment]
So I managed to make the script work with optimize image enabled by limiting CPU core usage and made a pull request for it but I am actually still running into the same issue ending up with over 25mbs of screenshots when uploading to MTV. Not sure if the fix that was pushed wasn't working properly as it did not attempt to drop any screenshots to lower the size. 
![image](https://github.com/user-attachments/assets/79c7fe66-8a3a-4e56-a4ff-e393c578dfc6)
![image](https://github.com/user-attachments/assets/31aa8aad-6f22-4a79-bf16-0ab929a4530a)
It doesn't really matter to me what the fix is as long as it works, even if it was just 1080p gets full size and 4k get thumbnails for MTV. If there is anything else I can try to do help just let me know

**Comment by Audionut** [comment]
Fist step is to check the meta. If you run with --debug, which will print the meta to screen, or better, open an existing meta.json file in the tmp directory, do you see the image_size meta?

``` json
    "image_sizes": {
        "https://ptpimg.me/5p4qbf.png": 2966567,
        "https://ptpimg.me/7vicjz.png": 3283115,
        "https://ptpimg.me/6rv6x4.png": 2364317,
        "https://ptpimg.me/7e53l0.png": 3988127
    },
    "image_list": [
        {
            "img_url": "https://ptpimg.me/6rv6x4.png",
            "raw_url": "https://ptpimg.me/6rv6x4.png",
            "web_url": "https://ptpimg.me/6rv6x4.png"
        },
        {
            "img_url": "https://ptpimg.me/5p4qbf.png",
            "raw_url": "https://ptpimg.me/5p4qbf.png",
            "web_url": "https://ptpimg.me/5p4qbf.png"
        },
        {
            "img_url": "https://ptpimg.me/7vicjz.png",
            "raw_url": "https://ptpimg.me/7vicjz.png",
            "web_url": "https://ptpimg.me/7vicjz.png"
        },
        {
            "img_url": "https://ptpimg.me/7e53l0.png",
            "raw_url": "https://ptpimg.me/7e53l0.png",
            "web_url": "https://ptpimg.me/7e53l0.png"
        }
    ],
```

**Comment by TJZine** [comment]
from meta.json on the failed upload from earlier tonight: 
```json
	"image_sizes": {},
    "image_list": [
        {
            "web_url": "https://imgbox.com/HpKbs4Pz",
            "img_url": "https://thumbs2.imgbox.com/90/06/HpKbs4Pz_t.png",
            "raw_url": "https://images2.imgbox.com/90/06/HpKbs4Pz_o.png"
        },
        {
            "web_url": "https://imgbox.com/x4GxVglg",
            "img_url": "https://thumbs2.imgbox.com/08/e5/x4GxVglg_t.png",
            "raw_url": "https://images2.imgbox.com/08/e5/x4GxVglg_o.png"
        },
        {
            "web_url": "https://imgbox.com/LHxnjmcy",
            "img_url": "https://thumbs2.imgbox.com/4f/43/LHxnjmcy_t.png",
            "raw_url": "https://images2.imgbox.com/4f/43/LHxnjmcy_o.png"
        },
        {
            "web_url": "https://imgbox.com/QQ9auFZv",
            "img_url": "https://thumbs2.imgbox.com/03/db/QQ9auFZv_t.png",
            "raw_url": "https://images2.imgbox.com/03/db/QQ9auFZv_o.png"
        },
        {
            "web_url": "https://imgbox.com/xKFmcAnl",
            "img_url": "https://thumbs2.imgbox.com/fc/1d/xKFmcAnl_t.png",
            "raw_url": "https://images2.imgbox.com/fc/1d/xKFmcAnl_o.png"
        },
        {
            "web_url": "https://imgbox.com/A8uxPVJp",
            "img_url": "https://thumbs2.imgbox.com/bf/45/A8uxPVJp_t.png",
            "raw_url": "https://images2.imgbox.com/bf/45/A8uxPVJp_o.png"
        }
    ]
```

**Comment by Audionut** [comment]
ofc it was imgbox.

The latest fix should work, I'm just fully verifying now.

**Comment by TJZine** [comment]
Running into the presentation error again which I had to confirm testing as a manual upload as the screenshot sizes in the directory were only ~21MiB
![image](https://github.com/user-attachments/assets/8002e66b-c978-4c44-bb85-526a8a02da54)
but after filling out the manual upload on MTV it shows above the 25MiB limit and I am unsure where the extra space is being used. 
![image](https://github.com/user-attachments/assets/c4641634-2417-4732-a389-9e85c8fff59f)
Very confusing to me as all I did was have it fill the upload form based on the torrent file created by L4G then added the description that only has media info followed by the screenshots
![image](https://github.com/user-attachments/assets/89858b7f-3a0a-4ce0-a95f-f58c823cb184)
Kind of lost as to what would be a good solution for this if there is more to the presentation size calculation than just the screenshots.

**Comment by Audionut** [comment]
![Screenshot 2024-10-23 172109](https://github.com/user-attachments/assets/88809362-6670-46a0-8205-5c1eb3c94ab8)
imgbox is messing with the files, let me think of the best solution.

**Comment by TJZine** [comment]
So its getting the sizes correctly and everything now 
![image](https://github.com/user-attachments/assets/9b6e9b81-ac02-47fa-aaf7-2dfa1d9ccaef)
but I don't think its ever actually running enforce_size_limit in MTV.py as I am still getting an error and no images are being removed from the description of the upload
![image](https://github.com/user-attachments/assets/942aaf8d-aa94-4698-9404-c8e8f8e73128)

**Comment by Audionut** [comment]
I could have sworn I checked this, sorry. It was checking the images fine, just some dumb dumb was sending thumbnails into the enforce_size_limit, _and_ not returning _only_ the valid_images.
